title: FIREして自由に暮らすためにAIと日々勉強
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/blog" # the subpath of your site, e.g. /blog
sass:
  sass_dir: _sass
  style: compressed
include:
  - assets
defaults:
  - scope:
      path: "assets/main.scss"
    values:
      sass: true
destination: _site
permalink: /:year/:month/:day/:title.html
url: "https://tool-cloud.github.io/blog/" # the base hostname & protocol for your site, e.g. https://
future: true  # 未来の日付の投稿を許可する場合
collections:
  category:
    output: true
defaults:
  - scope:
      path: "category"
      type: "category"
    values:
      layout: "category"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# theme: minima
plugins:
  - jekyll-feed

